name: awesome_env2.0
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - python==3.10.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  # - gcc_linux-64=9.3.0
  # - gxx_linux-64=9.3.0
  - gcc=8.5.0
  - gxx=8.5.0
  - scikit-image
  - scikit-learn
  - ninja
  - numpy<=1.23.5
  - numba=0.57.0